name: Auto_Get_VCB_Rates

on:
  schedule:
    - cron: '0 * * * *' # Chạy vào phút thứ 0 của mỗi giờ
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền cho robot được ghi file vào repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas openpyxl

      - name: Run scraper
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ty_gia_vcb.xlsx
          git commit -m "Cập nhật tỷ giá $(date)" || exit 0
          git push
