name: Auto_Get_VCB_Rates

on:
  schedule:
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas gspread oauth2client

      - name: Create credentials file
        run: |
          echo '${{ secrets.GSPREAD_JSON }}' > credentials.json

      - name: Run scraper
        run: python main.py
